# Generated by Django 3.1.8 on 2021-06-28 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(null=True, related_query_name='Song.playlist', to='umlapp.Song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_query_name='User.playlist', to='umlapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, related_query_name='Playlist.song', to='umlapp.Playlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='Playlist.user', to='umlapp.playlist'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='User.favorite', to='umlapp.user')),
                ('song', models.ManyToManyField(null=True, to='umlapp.Song')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umlapp.favorite'),
        ),
    ]
