# Generated by Django 3.1.8 on 2021-06-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0002_auto_20210628_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='playlist',
        ),
        migrations.AddField(
            model_name='user',
            name='playlist',
            field=models.ManyToManyField(blank=True, null=True, related_query_name='Playlist.user', to='umlapp.Playlist'),
        ),
    ]
