# Generated by Django 3.1.8 on 2021-06-27 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0002_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='umlapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(to='umlapp.Playlist'),
        ),
    ]
