# Generated by Django 3.1.8 on 2021-06-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0002_playlist_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='author',
        ),
    ]
