# Generated by Django 3.1.8 on 2021-06-27 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0003_auto_20210627_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umlapp.user')),
                ('song', models.ManyToManyField(to='umlapp.Song')),
            ],
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
