# Generated by Django 3.1.8 on 2021-06-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0003_auto_20210628_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='playlist',
        ),
    ]
