# Generated by Django 3.1.8 on 2021-06-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0004_auto_20210627_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
