# Generated by Django 3.1.8 on 2021-07-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0005_song_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='song',
            name='video',
        ),
    ]
