# Generated by Django 3.1.8 on 2021-06-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0005_auto_20210627_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_query_name='Song.Playlist', to='umlapp.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='umlapp.favorite'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='playlist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_query_name='Playlist.user', to='umlapp.playlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='User.favorite', to='umlapp.user'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='User.playlist', to='umlapp.user'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(related_query_name='Playlist.song', to='umlapp.Playlist'),
        ),
    ]
