# Generated by Django 3.1.8 on 2021-06-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0007_auto_20210627_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='User.favorite', to='umlapp.user'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='Song.Playlist', to='umlapp.song'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='User.playlist', to='umlapp.user'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, related_query_name='Playlist.song', to='umlapp.Playlist'),
        ),
    ]
