# Generated by Django 3.1.8 on 2021-06-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0011_auto_20210628_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, related_query_name='Playlist.song', to='umlapp.Playlist'),
        ),
    ]
