# Generated by Django 3.1.8 on 2021-06-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umlapp', '0012_auto_20210628_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='song',
            field=models.ManyToManyField(null=True, to='umlapp.Song'),
        ),
    ]
